export {
  getRequestDetailsTitle,
  getReviewEditRequestTitle,
  REQUEST_DETAILS_NO_DOCUMENTS_TEXT,
  REQUEST_DETAILS_NO_PHOTOS_TEXT,
  REQUEST_DETAILS_REVIEW_COMMENT_HELPER,
  REQUEST_DETAILS_REVIEW_COMMENT_LABEL,
  REQUEST_DETAILS_REVIEW_SUBTITLE,
  REQUEST_DETAILS_UPLOADED_DOCUMENTS_TITLE,
  REQUEST_DETAILS_UPLOADED_PHOTOS_TITLE,
  REQUEST_DETAILS_VIEW_SUBTITLE,
} from "./messages";

export {
  REQUEST_DETAILS_SECTION_TITLE_SX,
  REQUEST_DETAILS_SUBTITLE_SX,
  REQUEST_DETAILS_TITLE_SX,
} from "./styles";
